# Büyük Sayılar Yasası (The Law of Large Numbers (LLN))

🧑🏻‍🏫 LLN nedir? [Wikipedia'ya göre](https://en.wikipedia.org/wiki/Law_of_large_numbers)

> Bu teorem, olasılık teorisindeki temel sonuçlardan biridir. **Aynı deneyin çok sayıda kez yapılmasının sonuçlarını** açıklar. 

>Bu yasaya göre, çok sayıda denemeden elde edilen sonuçların ortalaması, beklenen değere yani teorik ortalama değere yakın olmalıdır ve deneme sayısı arttıkça ortalama değer beklenen değere daha da yaklaşacaktır.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 🎲 Zar atma

🎲 Zar atmak, 1, 2, 3, 4, 5, 6 olmak üzere 6 olası sonucu olan rastgele bir deneydir.

🤔 Peki bir Jupyter Notebook içinde nasıl zar atarım?

👉 [numpy.random.randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) `low`  (dahil) ve `high` (hariç) arasında rastgele bir tam sayı döndürür.

In [2]:
# Bu hücreyi birçok kez çalıştır
np.random.randint(1, 6+1)

4

* Bu hücreyi her çalıştırdığında, bir zar atıyorsun ve bu deneyin sonucu tamamen rastgele (1, 2, 3, 4, 5 veya 6). Buna basitçe bir **`random experiment`** (rastgele deney) diyoruz. 
* ❓Aynı anda 3 tane zar nasıl atılır?   [numpy.random.randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) dokümanını oku ve bu üç zarı at. ❓

In [3]:
np.random.randint(1, 6+1, 3)

array([1, 2, 2])

array([3, 1, 1])

🚀Şimdi, zarımızı`n = 20` kez atalım ve sonuçların ortalamasını hesaplayalım.
Sonuçları `outcomes` adlı bir değişkende, bu sonuçların ortalamasını ise `average_outcome` adlı bir değişkende sakla. 

In [ ]:
n = 20 # number of times you are rolling your dice

outcomes = np.random.randint(1, 6+1, n)

average_outcome = np.mean(outcomes)

In [ ]:
outcomes

array([5, 4, 1, 6, 1, 3, 5, 2, 3, 1, 3, 3, 3, 6, 3, 3, 5, 5, 5, 6])

In [ ]:
average_outcome

3.65

🤔 Beklediğin ortalama değer neydi?
Bu değeri `expected_value` adlı bir değişkene kaydet. 

In [ ]:
expected_value = 3.5

In [ ]:
from nbresult import ChallengeResult

result = ChallengeResult('expected_value_dice',
    expected_value=expected_value
)
result.write()
print(result.check())

<details>
    <summary>Explanations <i>(Bu bölümü açmadan önce beklenen ortalama değeri biraz düşün!)</i></summary>

"Zar atma" adlı rastgele deneyin olası sonuçlarını ve ilgili olasılıklarını aşağıdaki tabloda gösterebiliriz.


| Possible outcomes | 1   | 2   | 3   | 4   | 5   | 6   | Total |
|-------------------|-----|-----|-----|-----|-----|-----|-------|
| Probabilities     | 1/6 | 1/6 | 1/6 | 1/6 | 1/6 | 1/6 | 100%  |
    
 `expected/theoretical average value` Beklenen/teorik ortalama değer şu şekilde hesaplanabilir:
    

$$ \mathbb{E}[X] = 1 \times \frac{1}{6} + 2 \times \frac{1}{6} + 3 \times \frac{1}{6} + 4 \times \frac{1}{6} + 5 \times \frac{1}{6} + 6 \times \frac{1}{6} = 3.5 $$
 
Burada `X` , zar atma deneyinin rastgele sonucunu ifade eder.

👉 Bu nedenle `X`  'e bir `random variable` (rastgele değişken) deriz. 

</details>

--- 

🔥 Şimdi 🎲 zar atma deneyi için Büyük Sayılar Yasası’nı doğrulayalım.

***Questions :***

👉 Deneme sayısıyla oynayarak her bir durumda elde edilen ortalama sonucu hesapla.

🎨 Ortalama sonucu deneme sayısına karşı plot et.

**Steps to code (pseudo-code)**:

1. Denemek istediğin deneme sayılarını belirle (1, 2, 3, 4, … seçtiğin maksimum sayıya kadar). Bu aralığı `trials` adlı bir değişkende sakla.
2. Sonuçları saklamak için boş bir liste `results` oluştur.
3.`trials` içindeki her değer için:
-Zarı o sayı kadar at ve sonuçları sakla
-Sonuçların ortalamasını hesapla
-Hesaplanan ortalamayı `results` listesine kaydet
4.`results` değerlerini `trials`değerlerine karşı plot et (aşağıda bu plot kodu verildi)

In [ ]:
#############################################
#               expected value              #
#############################################

expected_value = 3.5

In [ ]:
#############################################
#     playing with the number of trials     #
#############################################

number_of_trials = 5000 # play with this number
trials = np.arange(1, number_of_trials + 1, 1)
results = []

# Step-by-step version
for n in trials:
    # roll your dice n times
    tmp = np.random.randint(1, 6+1, n)
    # compute the average outcome of these n dice
    average_outcome = np.mean(tmp)
    # store it in the list of results
    results.append(average_outcome)

In [ ]:
# One-liner version
results = []
for n in trials:
    results.append(np.mean(np.random.randint(1, 6+1, n)))

In [ ]:
# One-liner version with list comprehensions
results = [np.mean(np.random.randint(1, 6+1, n)) for n in trials]

In [ ]:
#############################################
#         sonuçları plot et          #
#############################################
    
    
plt.figure(figsize=(20,10))

plt.scatter(
    x=trials,
    y=results,
    label='Empirical mean for experiment',
    s=8
)
plt.plot(
    [expected_value]*len(results),
    label='Theoretical mean',
    color="red"
)

plt.title('Law of Large Numbers : The empirical mean converges towards the theoretical mean')
plt.xlabel('Number of trials in experiment')
plt.ylabel('Experiment mean')

plt.legend(loc='best')
plt.show()

🎉 Görsel olarak fark edebiliyoruz ki `empirical mean (ortalama)`  $ \bar{X_n} = \frac{X_1 + X_2 + ... + X_{n-1} + X_n}{n}$   deneme sayısı n  arttıkça `beklenen değere ` $ \mu = 3.5 $  yaklaşıyor!

## 🪙 Yazı-Tura atma (coin toss)

### One time

👉 Şimdi aynı deneyi bu kez yazı–tura atarak yapalım.

Artık sonuçlar 0 ve 1.

Deneyi 100 kez çalıştırırsan, büyük olasılıkla yaklaşık 50 tura – 50 yazı elde edersin.
* “Tura”yı başarılı bir deney olarak tanımlayalım ve $p$’yi tura gelme olasılığı olarak düşünelim. Sezgisel olarak:  $ p = \frac{1}{2} = 0.5 = 50 \%$

🤓 İki olası sonucu olan (başarı / başarısızlık)  `success/failure` $p$ as olan bir rastgele deneyin, parametresi p olan bir **`Bernoulli distribution`** izlediği söylenir; burada  `p` $ \in [0,1] $

🔥 Şimdi bu yazı–tura deneyi için Büyük Sayılar Yasasını `Law of Large Numbers` doğrulayalım. 

***Questions :***

👉 `Aşağıdaki hücrede deneme sayısıyla oynayın` ve deneme sayısına karşı ortalama sonucu gösteren grafiği inceleyin.

In [ ]:
number_of_trials = 500 # bu numaralarla oynayın
p = 0.5 # beklenen değer

In [ ]:
#############################################
#    deneme sayısıyla oynamak               #
#############################################
trials = np.arange(1,number_of_trials + 1,1)
results = [np.mean(np.random.randint(0, 1+1, n)) for n in trials]
    
#############################################
#         sonuçları plot et         #
#############################################
        
plt.figure(figsize=(20,10))

plt.scatter(
    x=trials,
    y=results, 
    label='Empirical mean for experiment',
    s=8
)
plt.plot(
    [p]*len(results),
    label='Theoretical mean', 
    color="red"
)

plt.title('Law of Large Numbers : The empirical mean converges towards the theoretical mean')
plt.xlabel('Number of trials in experiment')
plt.ylabel('Experiment mean')

plt.legend(loc='best')
plt.show()

"output.png" dosyasını kontrol ediniz. 

🎉 Görsel olarak fark edebiliyoruz ki `empirical mean (ortalama)`  $ \bar{X_n} = \frac{X_1 + X_2 + ... + X_{n-1} + X_n}{n}$ `deneme sayısı n arttıkça beklenen değere ` $ \mu = 0.5 $  *yaklaşıyor* !

### Multiple times

👉Burada,  ***TEK bir deney***  şunlardan oluşur:
* Yazı–tura atmayı `n_times` n kez yapmak
* Her denemenin p olasılıkla `probability p` başarılı olması

👉 Bir deneyi çalıştırdıktan sonra, başarı sayısını hiç başarı olmaması ile n_times kadar başarı `n_times successes` arasında sayabiliriz.

📚 Şu özelliklere sahip bir rastgele deney:
- iki olası sonuç: `success/failure`
- `p` $ \in [0,1] $ başarı olasılığı `probability of success`
- `n` $ \in \mathbb{N} $ deneme sayısı

 **`Binomial distribution (n,p)`**  dağılımını izler.

😉 Düşünürsen, **`Binomial dağılımı (n,p), n adet bağımsız Bernoulli(p) rastgele değişkeninin toplamıdır!`** !

---

❓ Aşağıdaki hücrede, Python’da TEK bir Binomial deneyi simüle etmek için  [numpy.random.binomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html) fonksiyonunu kullan: 

- $p = 0.7$ (yani yazı–tura biased olsun)
- $n = 10$ deneme



In [ ]:
# Bu hücreyi bir Binom Deneyi'nin 
# tek bir gerçekleşmesi için birden fazla kez çalıştır

n = 10  # yazı–tura n kez atmak
p = 0.7 # başarı olasılığı p ile tanımlanmış

# $CHALLENGIFY_BEGIN
print(f"Tossing a (unfair) coin {n} times with a probability {p} of getting a head...")
print("-"*5)

result = np.random.binomial(n=n, p=p, size=1)
print(f"result = {result}")

print("-"*5)
print(f"Among these {n} coins, {result[0]} were HEADS (and {n - result[0]} turned out to be TAILS)")
# $CHALLENGIFY_END

❓ Şimdi bu deneyi $N = 20$ kez tekrar et ve bu 20 sonucun her birini bir liste içinde sakla.

<details>
    <summary><i>Hint</i></summary>
    
Bu hücreyi birkaç kez çalıştır ve rastgeleliği gözlemle…!
    
</details>

In [ ]:
# Bu hücreyi bir Binom Deneyi'nin 
# N adet gerçekleşmesi için birden fazla kez çalıştır

N = 20  # deney sayısı
n = 10  # yazı–tura n kez atmak
p = 0.7 # başarı olasılığı p ile tanımlanmış

# $CHALLENGIFY_BEGIN
my_realisations = np.random.binomial(n = n, p = p,size = N)

print(f"On average, among my {N} realisations, I had on average {np.mean(my_realisations)} successes out of {n} coins tossed")
# $CHALLENGIFY_END


Tossing a (unfair) coin 10 times with a probability 0.7 of getting a head...
-----
result = [7]
-----
Among these 10 coins, 7 were HEADS (and 3 turned out to be TAILS)


🔥 Şimdi, bu birden fazla yazı–tura atma deneyi için `Law of Large Numbers` doğrulayalım. 

*** Sorular:***

🤔 Beklediğin ortalama değer neydi? Bunu `expected_value_coins` adlı bir değişkende sakla.

In [ ]:
expected_value_coins = None

In [ ]:
from nbresult import ChallengeResult

result = ChallengeResult('expected_value_coins',
    expected_value_coins=expected_value_coins
)
result.write()
print(result.check())

<details>
    <summary>Açıklamalar</summary>

💡 $n = 10$ yazı–tura atışı ve $p = 0.7$ için, bir Binom deneyinde beklenen başarı sayısı: $ n \times p = 10 \times 0.7 = 7$ 
    
📚 Bu sonuç, herhangi bir `Binomial(n,p)` rastgele deneyi için geçerlidir! 
    
$$ \mathbb{E}[X] = np $$
    
</details>

📈 Bu sonuçları aşağıda görselleştir.

In [ ]:
#############################################
#    deneme sayısıyla oynama                #
#############################################
p = 0.7
n = 10
N = 1000

trials = np.arange(1, N+1, 1)
results = [np.mean(np.random.binomial(n=n,p=p, size=N)) for N in trials]
    
#############################################
#           sonuçları plot et               #
#############################################
    
    
plt.figure(figsize=(20,10))

plt.scatter(
    x=trials,
    y=results,
    label='Empirical mean for experiment',
    s=10
)
plt.plot([expected_value_coins]*len(results),label='mu', color = "red")

plt.title('Law of Large Numbers : The empirical mean converges towards the theoretical mean')
plt.xlabel('Number of trials in experiment')
plt.ylabel('Experiment mean')

plt.legend(loc='best')
plt.show()

output1.png dosyasını kontrol ediniz.

🏁  Tebrikler!!!

🔥 Olasılık Teorisinin en temel teoremlerinden biri olan Büyük Sayılar Yasası’nı başarıyla öğrendin.

💾 Challenge’ını `add/commit/push` yapmayı unutma!

---

***Ek kaynaklar***

📺 [Law of Large Numbers - Explained and Visualized](https://www.youtube.com/watch?v=MntX3zWNWec)  Jeremy Blitz-Jones (4 dk 11 saniye)

